version: '3'
services:
  # db:
  #   image: postgres
  web:
    build: .
    volumes:
      - ../env:/home/app/env
    ports:
      - "80:80"
    tty: true
    #     command: [ "python3", "/home/app/src/hello.py" ]
    #    entrypoint: /home/app/src/run_hello.sh
    # docker-compose exec sh run_hello.sh
    # docker-compose exec python3 hello.py
    # depends_on:
    #   - db
    # memo 
    # docker ps -q get only container id 
